import { date, int, mysqlTable, text, varchar } from 'drizzle-orm/mysql-core';

export const proposal = mysqlTable('proposal', {
    id: int('id').primaryKey().autoincrement(),
    emp_id: int('emp_id'),
    refno: varchar('refno', { length: 50 }),
    proposaltype: varchar('proposaltype', { length: 30 }),
    title: text('title').notNull(),
    principal: varchar('principal', { length: 50 }),
    coprincipal: varchar('coprincipal', { length: 50 }),
    applydate: date('applydate'),
    sanctiondate: date('sanctiondate'),
    fund: varchar('fund', { length: 100 }),
    FundAgency: varchar('FundAgency', { length: 50 }),
    budget: int('budget'),
    durationfrom: date('durationfrom'),
    durationto: date('durationto'),
    duration: int('duration'),
    samt: int('samt').default(0),
    brief: text('brief'),
    ryear1: int('ryear1'),
    ryear2: int('ryear2'),
    ryear3: int('ryear3'),
    ryear4: int('ryear4'),
    ryear5: int('ryear5'),
    uyear1: int('uyear1'),
    uyear2: int('uyear2'),
    uyear3: int('uyear3'),
    uyear4: int('uyear4'),
    uyear5: int('uyear5'),
    uc1: varchar('uc1', { length: 200 }),
    uc2: varchar('uc2', { length: 200 }),
    uc3: varchar('uc3', { length: 200 }),
    uc4: varchar('uc4', { length: 200 }),
    uc5: varchar('uc5', { length: 200 }),
    Publications: text('Publications'),
    pstatus: varchar('pstatus', { length: 20 }),
    report: text('report'),
});
