// drizzle-orm schema for employee_master_non_teaching
import { datetime, int, mysqlTable, text, tinyint, varchar } from 'drizzle-orm/mysql-core';

export const employeeMasterNonTeaching = mysqlTable('employee_master_non_teaching', {
  id: int('id').primaryKey().autoincrement(),
  emp_id: varchar('emp_id', { length: 15, nullable: true }),
  first_name: varchar('first_name', { length: 300, nullable: true }),
  last_name: varchar('last_name', { length: 30, nullable: true }),
  off_email: varchar('off_email', { length: 60, nullable: true }),
  password: varchar('password', { length: 50, nullable: true }),
  DispOrder: int('DispOrder', { nullable: true }),
  status: int('status', { nullable: true }),
  dob: varchar('dob', { length: 12, nullable: true }),
  doj: varchar('doj', { length: 13, nullable: true }),
  gender: varchar('gender', { length: 1, nullable: true }),
  blood_group: varchar('blood_group', { length: 10, nullable: true }),
  per_email_1: varchar('per_email_1', { length: 60, nullable: true }),
  per_email_2: varchar('per_email_2', { length: 60, nullable: true }),
  mobile_1: varchar('mobile_1', { length: 14, nullable: true }),
  mobile_2: varchar('mobile_2', { length: 14, nullable: true }),
  address_1: text('address_1', { nullable: true }),
  address_2: text('address_2', { nullable: true }),
  photo: varchar('photo', { length: 60, nullable: true }),
  resume: varchar('resume', { length: 60, nullable: true }),
  father_name: varchar('father_name', { length: 50, nullable: true }),
  mother_name: varchar('mother_name', { length: 50, nullable: true }),
  pan_no: varchar('pan_no', { length: 50, nullable: true }),
  pan_name: varchar('pan_name', { length: 50, nullable: true }),
  pass_no: varchar('pass_no', { length: 50, nullable: true }),
  bank_no: varchar('bank_no', { length: 50, nullable: true }),
  created: datetime('created', { nullable: true }),
  stage1: int('stage1', { nullable: true }),
  stage2: int('stage2', { nullable: true }),
  stage3: int('stage3', { nullable: true }),
  stage4: int('stage4', { nullable: true }),
  stage5: int('stage5', { nullable: true }),
  place: tinyint('place', { nullable: true }),
  designation: varchar('designation', { length: 60, nullable: true }),
  EMPTYPE: varchar('EMPTYPE', { length: 5, nullable: true }),
  dept: varchar('dept', { length: 60, nullable: true }),
  promotwo: varchar('promotwo', { length: 40, nullable: true }),
});
